### ISSUE TITLE
How to use S1 output this modules...

### ISSUE THREAD

**Issue by CHAUHAN428** [Seeed-Studio/Seeed_Arduino_24GHz_Radar_Sensor#3]
Hi..i need to use S1 output for led on and off. when there is person led should light up..and when no one in range ..led should off ...i tied using S1 to led positive and but S1 always continue 3.3 v..even if no one in range

**Comment by lakshanthad** [comment]
Hello,

Could you please share the code that you tried?

Thank you

**Comment by posgod** [comment]
> Hi..i need to use S1 output for led on and off. when there is person led should light up..and when no one in range ..led should off ...i tied using S1 to led positive and but S1 always continue 3.3 v..even if no one in range

I'm seeing the same issue. S2 seems to go high and low as I move in front of the sensor but so far S1 has always measured high.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Does this problem still exist? If so, can you provide a reproducible environment?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
